spring:
  datasource:
    #    驱动
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meowsauce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: root
    username: root
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    database: 0
    timeout: 2000
  data:
    redis:
      repositories:
        enabled: false
#  单个文件大小以及单次请求文件总大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8443
  reactive:
    session:
      timeout: 300
